language: generic
sudo: required # required for travis to use docker
services:
  - docker

before_install:
  - docker build -t robinerickson/docker-react -f Dockerfile.dev .

script:
  # -e CI=true sets env variable telling travis to only run the test once, not in watch mode
  - docker run -e CI=true robinerickson/docker-react npm run test